// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwhebwrtfzkbobqdqimq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3aGVid3J0ZnprYm9icWRxaW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2MDc1MTksImV4cCI6MjA4NDE4MzUxOX0.Z4HKhB4l7QoDvQWMdhYRs0ecuaFoUGXuIwPtYa3yOj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});